src/Entity/Caracteristic.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\CaracteristicModifier;
use App\Repository\CaracteristicRepository;
use SplObserver;

#[ORM\Entity(repositoryClass: CaracteristicRepository::class)]
class Caracteristic
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $intelligence = 0;

    #[ORM\OneToOne(mappedBy: 'caracteristic', cascade: ['persist', 'remove'])]
    private ?Card $card = null;

    #[ORM\OneToOne(mappedBy: 'caracteristic', cascade: ['persist', 'remove'])]
    private ?CaracteristicModifier $intelligenceModifier = null;

    #[ORM\Column]
    private ?int $strength = 0;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?CaracteristicModifier $strengthModifier = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntelligenceDetails(): array
    {
        return [
            'basic' => $this->intelligence,
            'bonus' => $this?->getIntelligenceModifier()?->getQuantity() ?? 0,
            'duration' => $this?->getIntelligenceModifier()?-> getDuration() ?? 0
        ];
    }

    public function getIntelligence(): ?int
    {
        $durationModifier = 1;
        if ($this->getIntelligenceModifier()?->getDuration() !== null && $this->getIntelligenceModifier()->getDuration() <= 0) {
            $durationModifier = 0;
        }

        return $this->intelligence + $this->getIntelligenceModifier()?->getQuantity() * $durationModifier;
    }

    public function setIntelligence(int $intelligence): self
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getCard(): ?Card
    {
        return $this->card;
    }

    public function setCard(?Card $card): self
    {
        // unset the owning side of the relation if necessary
        if ($card === null && $this->card !== null) {
            $this->card->setCaracteristic(null);
        }

        // set the owning side of the relation if necessary
        if ($card !== null && $card->getCaracteristic() !== $this) {
            $card->setCaracteristic($this);
        }

        $this->card = $card;

        return $this;
    }

    public function getIntelligenceModifier(): ?CaracteristicModifier
    {
        return $this->intelligenceModifier;
    }

    public function setIntelligenceModifier(?CaracteristicModifier $intelligenceModifier): self
    {
        // unset the owning side of the relation if necessary
        if ($intelligenceModifier === null && $this->intelligenceModifier !== null) {
            $this->intelligenceModifier->setCaracteristic(null);
        }

        // set the owning side of the relation if necessary
        if ($intelligenceModifier !== null && $intelligenceModifier->getCaracteristic() !== $this) {
            $intelligenceModifier->setCaracteristic($this);
        }

        $this->intelligenceModifier = $intelligenceModifier;

        return $this;
    }

    public function getStrength(): ?int
    {
        return $this->strength;
    }

    public function setStrength(int $strength): self
    {
        $this->strength = $strength;

        return $this;
    }

    public function getStrengthModifier(): ?CaracteristicModifier
    {
        return $this->strengthModifier;
    }

    public function setStrengthModifier(?CaracteristicModifier $strengthModifier): self
    {
        $this->strengthModifier = $strengthModifier;

        return $this;
    }
}

templates/fight/_action.html.twig
<div class="card bg-warning">
	<img src="{{ asset('build/images/actions/' ~ action.image )}}" class="card-img" alt="...">
	<a href="play/{{ action.identifier }}" class="">
		<div class="card-img-overlay">
			<h3 class="card-title">{{ action.name }}</h3>
			<p class="card-text">{{ action.description ?? '' }}</p>
		</div>
	</a>
</div>

templates/fight/_card.html.twig
<div class="card
	{% if app.session.get('actioner').attacker is not null %}
		{{ app.session.get('actioner').attacker == card ? 'attacker' : 'not-attacker' }}
	{% endif %}

	{{ possibleTargets is defined and card in possibleTargets ? 'targetable' }}">
	<img src="{{ asset('build/images/cards/' ~ card.image )}}" class="card-img" alt="{{ card.name }}">
	<a href="play/{{ card.identifier }}">
		<div class="card-img-overlay">
			<h3 class="card-title">{{ card.name }}</h3>
			<p class="card-text">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewbox="0 0 16 16">
					<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
				</svg>
				{{ card.life }}</p>
			<p class="card-text">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-magic" viewbox="0 0 16 16">
					<path d="M9.5 2.672a.5.5 0 1 0 1 0V.843a.5.5 0 0 0-1 0v1.829Zm4.5.035A.5.5 0 0 0 13.293 2L12 3.293a.5.5 0 1 0 .707.707L14 2.707ZM7.293 4A.5.5 0 1 0 8 3.293L6.707 2A.5.5 0 0 0 6 2.707L7.293 4Zm-.621 2.5a.5.5 0 1 0 0-1H4.843a.5.5 0 1 0 0 1h1.829Zm8.485 0a.5.5 0 1 0 0-1h-1.829a.5.5 0 0 0 0 1h1.829ZM13.293 10A.5.5 0 1 0 14 9.293L12.707 8a.5.5 0 1 0-.707.707L13.293 10ZM9.5 11.157a.5.5 0 0 0 1 0V9.328a.5.5 0 0 0-1 0v1.829Zm1.854-5.097a.5.5 0 0 0 0-.706l-.708-.708a.5.5 0 0 0-.707 0L8.646 5.94a.5.5 0 0 0 0 .707l.708.708a.5.5 0 0 0 .707 0l1.293-1.293Zm-3 3a.5.5 0 0 0 0-.706l-.708-.708a.5.5 0 0 0-.707 0L.646 13.94a.5.5 0 0 0 0 .707l.708.708a.5.5 0 0 0 .707 0L8.354 9.06Z"/>
				</svg>
				{{ card.magic }}</p>
			<p class="card-text">Intelligence :
				{{ card.caracteristic.intelligenceDetails.basic ?? '' }}
				{% if card.caracteristic.intelligenceDetails.bonus %}
					{{ card.caracteristic.intelligenceDetails.bonus > 0 ? '+' : '-' }}
					{{ card.caracteristic.intelligenceDetails.bonus }}
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hourglass-split" viewbox="0 0 16 16">
						<path d="M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2h-7zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48V8.35zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z"/>
					</svg>
					{{ card.caracteristic.intelligenceDetails.duration }}
				{% endif %}
			</p>
		</div>
	</a>
</div>

templates/fight/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fight
{% endblock %}

{% block body %}
	<header class="d-flex bg-dark text-light align-items-center gap-3">
		<h1>Arena name</h1>
		<a class="btn btn-danger btn-sm" href="{{ path('reset') }}">Reset</a>
	</header>

	<main id="swup" class="container-fluid d-flex h-100 flex-column justify-content-beetween">
		{% for player in playerSwitcher.players %}
			<div class="d-flex justify-content-between m-3 p-3 {{ playerSwitcher.currentPlayer == player ? 'currentPlayer' : 'otherPlayer' }}">
				<div class="d-flex gap-2">
					{% for card in player.cards %}
						{% include 'fight/_card.html.twig' %}
					{% endfor %}
				</div>
				<div class="d-flex">
					{% for action in player.actions %}
						{% include 'fight/_action.html.twig' %}
					{% endfor %}
				</div>
			</div>
			{% if loop.first %}
				<div class="d-flex justify-content-center">
					<a class="btn btn-lg btn-light" href="play/fight">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-fill" viewbox="0 0 16 16">
							<path d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5z"/>
						</svg>
						Fight
					</a>
				</div>
			{% endif %}
		{% endfor %}
	</main>
{% endblock %}